name: python313-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip>=24.0
  # 在此添加项目所需的其他conda依赖
  # 例如:
  # - numpy>=1.26.0
  # - pandas>=2.2.0
  - pip:
    # 在此添加需要通过pip安装的依赖
    # 例如:
    # - requests>=2.32.0
    # - python-dotenv>=1.0.0
